# -*- coding: utf-8 -*-
"""tesis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AsM-bC8zuVhScHt1N7eK8yABy0e37Dt0
"""

#!pip install --upgrade obspy

# Librerías necesarias
from obspy import UTCDateTime, read_inventory, read
import requests
import urllib3
import numpy as np
import warnings
from obspy.io.mseed.headers import InternalMSEEDWarning
import openpyxl

def principal(np):
    #Lectura del excel
    wb = openpyxl.load_workbook('../Recursos/Variables_thor.xlsx')
    ws = wb.active

    for i in range(2,ws.max_row+1):
        print(ws.cell(row=i,column=2).value)

    row = 10
    while (row <= 1 or row > ws.max_row):
        row = int(input("Digite el indice del sismo: "))
    values = [ws.cell(row=row,column=i).value for i in range(1,ws.max_column+1)]
    print(values)
    print("============================")

    warnings.filterwarnings("ignore", category=InternalMSEEDWarning)

    # Desactiva advertencias de seguridad SSL (solo si confías en el sitio web)
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

    # ------------------------
    # 1. Descargar traza desde URL del OSSO
    # ------------------------

    # URL del archivo MiniSEED del día juliano 144 para estación RAFDA
    url = values[0]
    local_filename = values[1]

    # Descarga sin verificación SSL
    response = requests.get(url, verify=False)
    with open(local_filename, 'wb') as f:
        f.write(response.content)

    # ------------------------
    # 2. Definir ventana de análisis
    # ------------------------

    # Tiempo de inicio del evento
    inicio = UTCDateTime(values[2])
    # Duración de la ventana: 0.6 segundos
    fin = inicio + values[3]

    # ------------------------
    # 3. Leer traza y corregir respuesta instrumental
    # ------------------------

    # Cargar la traza desde el archivo descargado
    trace = read(local_filename,starttime=inicio,endtime=fin)

    # URL del archivo de respuesta en formato StationXML
    url_inv = values[4]
    inv_file = values[5]

    # Descargar archivo de respuesta
    response = requests.get(url_inv, verify=False)
    with open(inv_file, 'wb') as f:
        f.write(response.content)

    # Leer archivo de respuesta con ObsPy
    inv = read_inventory(inv_file)

    # Asociar respuesta a la traza y removerla para obtener velocidad en m/s
    trace.attach_response(inv)
    trace.remove_response(output="VEL")  # Resultado: velocidad (m/s)

    # Eliminar tendencia lineal y valor medio
    trace.detrend('linear')
    trace.detrend('demean')

    # Seleccionar traza corregida
    tr = trace[0]
    data = tr.data                 # Datos de velocidad (en m/s)
    dt = tr.stats.delta           # Intervalo de muestreo (en segundos)

    # Aplicar filtro de banda (0.1–50 Hz)
    sampling_rate = tr.stats.sampling_rate
    nyquist = 0.5 * sampling_rate
    freqmax = min(45.0, nyquist - 0.5)  # dejar margen de seguridad
    trace.filter("bandpass", freqmin=0.1, freqmax=freqmax, corners=4, zerophase=True)

    # Mostrar forma de onda en el intervalo de interés
    trace.plot(color='red', starttime=inicio, endtime=fin)

    # ------------------------
    # 4. Análisis de velocidad, desplazamiento y aceleración
    # ------------------------

    # Seleccionar traza corregida
    tr = trace[0]
    data = tr.data                 # Datos de velocidad (en m/s)
    dt = tr.stats.delta           # Intervalo de muestreo (en segundos)

    # --- ESTADÍSTICAS ---
    # Pico a pico (peak-to-peak) de velocidad
    Vpp = (np.max(data) - np.min(data)) * 1e3        # [mm/s]

    # Amplitud pico absoluta
    peak_amplitude = np.max(np.abs(data)) * 1e3      # [mm/s]
    # Tiempo absoluto de la amplitud pico
    peak_sample = np.argmax(np.abs(data))          # Índice de la amplitud máxima
    peak_time = inicio + peak_sample * dt  # Tiempo UTC exacto
    print(f"Tiempo pico absoluto: {peak_time}")
    print(f"Amplitud pico absoluta: {peak_amplitude:.3f} mm/s")

    import matplotlib.pyplot as plt
    import numpy as np  # Asegúrate de tener importado numpy

    # Filtrar el stream para obtener solo la traza deseada
    tr = trace[0]
    data = tr.data
    dt = tr.stats.delta
    times = np.linspace(0, tr.stats.npts * dt, tr.stats.npts)
    start = tr.stats.starttime

    # Calcular pico absoluto
    peak_sample = np.argmax(np.abs(data))
    peak_time_abs = start + peak_sample * dt
    peak_time_rel = times[peak_sample]  # Tiempo relativo para graficar
    peak_value_mm = data[peak_sample] * 1e3  # Convertir a mm/s

    import matplotlib.pyplot as plt
    import numpy as np

    # --- Configuración de estilo ---
    plt.style.use('seaborn-v0_8-notebook')  # Estilo moderno
    colors = {'disp': '#4e79a7', 'vel': '#e15759', 'acc': '#59a14f'}  # Paleta coherente

    # --- Datos base ---
    tr = trace[0]
    data = tr.data
    dt = tr.stats.delta
    times = np.linspace(0, (tr.stats.npts - 1) * dt, tr.stats.npts)  # Corrección de npts

    # --- Cálculos físicos ---
    velocity = data * 1e3  # mm/s
    tr_disp = tr.copy().integrate(method="cumtrapz")
    displacement = tr_disp.data * 1e3  # mm
    acceleration = np.gradient(data, dt) * 1e3  # mm/s²

    # --- Encontrar picos y valles ---
    def get_extremes(y):
        idx_max = np.argmax(y)
        idx_min = np.argmin(y)
        return (idx_max, y[idx_max]), (idx_min, y[idx_min])

    (disp_max_t, disp_max), (disp_min_t, disp_min) = get_extremes(displacement)
    (vel_max_t, vel_max), (vel_min_t, vel_min) = get_extremes(velocity)
    (acc_max_t, acc_max), (acc_min_t, acc_min) = get_extremes(acceleration)

    # --- VPP ---
    vpp_disp = disp_max - disp_min
    vpp_vel = vel_max - vel_min
    vpp_acc = acc_max - acc_min

    import matplotlib.pyplot as plt
    import numpy as np

    # --- Configuración de estilo ---
    plt.style.use('seaborn-v0_8-notebook')
    colors = {'disp': '#4e79a7', 'vel': '#e15759', 'acc': '#59a14f', 'freq': '#ff7f0e'}

    # --- Datos base ---
    tr = trace[0]
    data = tr.data
    dt = tr.stats.delta
    times = np.linspace(0, (tr.stats.npts - 1) * dt, tr.stats.npts)

    # --- Cálculos físicos ---
    velocity = data * 1e3  # mm/s
    tr_disp = tr.copy().integrate(method="cumtrapz")
    displacement = tr_disp.data * 1e3  # mm
    acceleration = np.gradient(data, dt) * 1e3  # mm/s²

    # --- Cálculo de cruces por cero ---
    zero_crossings = np.where(np.diff(np.sign(data)))[0]
    zero_crossing_times = times[zero_crossings]
    frequency_zero_crossings = len(zero_crossings) / (tr.stats.npts / tr.stats.sampling_rate)  # Hz

    # --- Encontrar picos y valles ---
    def get_extremes(y):
        idx_max = np.argmax(y)
        idx_min = np.argmin(y)
        return (idx_max, y[idx_max]), (idx_min, y[idx_min])

    (disp_max_t, disp_max), (disp_min_t, disp_min) = get_extremes(displacement)
    (vel_max_t, vel_max), (vel_min_t, vel_min) = get_extremes(velocity)
    (acc_max_t, acc_max), (acc_min_t, acc_min) = get_extremes(acceleration)

    # --- Figura 1: Señales con picos ---
    fig1, axes = plt.subplots(4, 1, figsize=(14, 14), sharex=True)

    def annotate_extreme(ax, time, value, label, color, offset_x=10, offset_y=10):
        ax.annotate(
            label,
            xy=(time, value),
            xytext=(offset_x, offset_y),
            textcoords='offset points',
            arrowprops=dict(
                arrowstyle="->",
                color=color,
                lw=1.5,
                connectionstyle="arc3,rad=0.3"
            ),
            bbox=dict(boxstyle='round,pad=0.5', fc='white', alpha=0.8),
            fontsize=9,
            color=color
        )

    # Subplot 1: Desplazamiento
    ax = axes[0]
    ax.plot(times, displacement, color=colors['disp'], lw=1.5)
    annotate_extreme(ax, times[disp_max_t], disp_max, f'Max: {disp_max:.2f} mm', 'red', 20, 20)
    annotate_extreme(ax, times[disp_min_t], disp_min, f'Min: {disp_min:.2f} mm', 'blue', 20, -30)
    ax.set_ylabel(f'Desplazamiento \n peak to peak: {vpp_disp:.3f} mm')
    ax.grid(True, linestyle='--', alpha=0.6)

    # Subplot 2: Velocidad
    ax = axes[1]
    ax.plot(times, velocity, color=colors['vel'], lw=1.5)
    annotate_extreme(ax, times[vel_max_t], vel_max, f'Max: {vel_max:.2f} mm/s', 'red', 20, 20)
    annotate_extreme(ax, times[vel_min_t], vel_min, f'Min: {vel_min:.2f} mm/s', 'blue', 20, -30)
    ax.set_ylabel(f'Velocity \n peak to peak: {vpp_vel:.3f} mm/s \n Peak Particle: {peak_value_mm:.3f} mm/s')
    ax.grid(True, linestyle='--', alpha=0.6)

    # Subplot 3: Aceleración
    ax = axes[2]
    ax.plot(times, acceleration, color=colors['acc'], lw=1.5)
    annotate_extreme(ax, times[acc_max_t], acc_max, f'Max: {acc_max:.2f} mm/s²', 'red', 20, 20)
    annotate_extreme(ax, times[acc_min_t], acc_min, f'Min: {acc_min:.2f} mm/s²', 'blue', 20, -30)
    ax.set_ylabel(f'Aceleración \n peak to peak: {vpp_acc:.3f} mm/s²')
    ax.grid(True, linestyle='--', alpha=0.6)

    # Subplot 4: Cruce por cero
    ax = axes[3]
    ax.plot(times, data, color=colors['freq'], lw=1, label='Señal original')
    ax.scatter(zero_crossing_times, np.zeros_like(zero_crossing_times),
            color='red', s=50, zorder=5, label='Cruces por cero')
    ax.axhline(0, color='gray', linestyle='--', alpha=0.5)
    ax.set_ylabel(f'Amplitud (mm/s)\nFZC: {frequency_zero_crossings:.3f} Hz')
    ax.legend()
    ax.grid(True, linestyle='--', alpha=0.6)
    ax.set_xlabel('Tiempo (s)')

    fig1.suptitle(f'ANALISÍS DE SEÑALES - {tr.id}\n  {inicio} - {fin}' , fontsize=14)
    plt.tight_layout()

    plt.show()